@jwt=eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMSwiZXhwIjoxNjUyMjg4MzYyfQ.3a_oOwBLZdKaxchW5RgiFesCBgwJ_RwnTJRKTJQkk2M

### posts show ###
GET http://localhost:3000/posts/3.json

### posts index ###
GET http://localhost:3000/posts.json

### posts create ###
POST http://localhost:3000/posts.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "title": "Cool",
  "text": "This is a fun game!",
  "game_id": 5
}

### posts update ###
PATCH http://localhost:3000/posts/6.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
 "title": "Nice"
}

### posts destroy ###
DELETE http://localhost:3000/posts/6.json
Authorization: Bearer {{jwt}}

### games show ###
GET http://localhost:3000/games/2.json

### games index ###
GET http://localhost:3000/games.json

### games create ###
POST http://localhost:3000/games.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "title": "title3",
  "genre": "genre3",
  "description": "description",
  "image_url": "image"
}

### games update ###
PATCH http://localhost:3000/games/17.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "title": "General",
  "genre": "Genereal"
}

### games destroy ###
DELETE http://localhost:3000/games/17.json
Authorization: Bearer {{jwt}}

### SESSION CREATE (login) ###
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "luna@test.com",
  "password": "password"
}

### USERS CREATE (signup) ###
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "username": "luna",
  "email": "luna@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### users show ###
GET http://localhost:3000/users/1.json

### users index ###
GET http://localhost:3000/users.json